### ISSUE TITLE
Sweep: 

### ISSUE THREAD

**Issue by loganbek** [loganbek/plague-gaming#9]
### Details

Absolutely, let's start by setting up a simple structure for the homepage. Once you upload the logo, I'll integrate it into the design. Here's a basic homepage structure for your Next.js application:

1. **Create a new component for the Navbar** (which will house the logo):
   
`components/Navbar.js`

```javascript
import React from 'react';

const Navbar = ({ logoSrc }) => {
  return (
    <nav className="navbar">
      <img src={logoSrc} alt="Plague Gaming Logo" className="logo" />
      {/* Other navbar items can be added here */}
    </nav>
  );
};

export default Navbar;
```

2. **Homepage structure**:

`pages/index.js`

```javascript
import React from 'react';
import Navbar from '../components/Navbar';

export default function Home() {
  return (
    <div className="container">
      <Navbar logoSrc="/path-to-your-logo.png" />
      
      <main className="main-content">
        <h1>Welcome to Plague Gaming</h1>
        <p>Your premier source for the latest and greatest in gaming.</p>
        {/* Other content sections can be added here */}
      </main>

      <footer className="footer">
        <p>© 2023 Plague Gaming. All rights reserved.</p>
      </footer>
    </div>
  );
}
```

3. **Simple styling** (you can expand upon this):

`styles/globals.css` (or whichever styling approach you're using)

```css
.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 20px;
  font-family: Arial, sans-serif;
}

.navbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 20px 0;
}

.logo {
  height: 50px;  /* Adjust based on your logo's size */
}

.main-content {
  padding: 40px 0;
}

.footer {
  padding: 20px 0;
  text-align: center;
  background-color: #f5f5f5;
}
```

Once you've uploaded the logo, replace `"/path-to-your-logo.png"` in the `Navbar` component with the correct path to your logo. If you're using the default Next.js `public` folder for static assets, your logo's path would be `"/logo.png"` (or whatever the filename and extension are).
